FROM openmedicus/centos-lamp:@PHP_VERSION@
MAINTAINER Mikkel Kruse Johnsen <mikkel@xmedicus.com>

RUN sed -i -e "s/\/var\/www\/html/\/var\/www\/html\/public_html/g" /etc/httpd/conf/httpd.conf
RUN sed -i -e "s/DirectoryIndex index\.html/DirectoryIndex index\.php index\.html/g" /etc/httpd/conf/httpd.conf

ADD phplist-@PHPLIST_VERSION@.tgz /
RUN mv phplist-@PHPLIST_VERSION@/* /var/www/html/ ; \
	chown -R apache:apache /var/www/html

